# Generated by Django 3.0.5 on 2021-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.PositiveIntegerField()),
                ('kp', models.PositiveIntegerField()),
                ('kd', models.PositiveIntegerField()),
                ('auto', models.BooleanField(default=True)),
                ('setpoint', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp', models.PositiveIntegerField()),
                ('Humid', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
