# Generated by Django 3.0.5 on 2021-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-created_at']},
        ),
    ]
