# Generated by Django 3.1.3 on 2021-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20211013_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='setpoint',
            new_name='setpoint_t',
        ),
        migrations.AddField(
            model_name='control',
            name='setpoint_h',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
