# Generated by Django 3.1.3 on 2021-10-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20211014_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='kd',
        ),
        migrations.RemoveField(
            model_name='control',
            name='ki',
        ),
        migrations.RemoveField(
            model_name='control',
            name='kp',
        ),
    ]
