# Generated by Django 3.1.3 on 2021-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20211014_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='kd_h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='kd_t',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='ki_h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='ki_t',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='kp_h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='kp_t',
            field=models.FloatField(null=True),
        ),
    ]
