# Generated by Django 3.1.3 on 2021-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20211017_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='led',
            old_name='on',
            new_name='on_h',
        ),
        migrations.AddField(
            model_name='led',
            name='on_t',
            field=models.BooleanField(default=True),
        ),
    ]
