# Generated by Django 3.1.3 on 2021-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20211017_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='setpoint_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='setpoint_t',
            field=models.IntegerField(),
        ),
    ]
