# Generated by Django 3.2.8 on 2021-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_auto_20211017_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='setpoint_h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='setpoint_t',
            field=models.FloatField(null=True),
        ),
    ]
